# Introduction

On average, flight delays cost the U.S. economy \$285 million and \$580 million per day ([FAA](https://www.airlines.org/news-update/new-data-shows-huge-impact-of-the-government-shutdown-on-airlines-and-our-customers/)). It also affects 236 million travelers, almost 1 in 4 passengers, each year ([Airhelp](https://www.airhelp.com/en/blog/us-passengers-flight-delays-and-cancellations-in-2024/)). To understand where and why these delays occur, we will analyse the on-time statistics and delay causes of U.S. domestic flights from January to June 2025. Our analysis will answer two key questions: (1) How do delay patterns vary across U.S. airports and states, and how are these patterns associated with geography, dominant delay types, and airport traffic volume? (2) Which delay type is most costly to the aviation system, and what are its underlying patterns and impacts? By examining five delay categories across major airports, we can identify systemic patterns as well as airport-specific challenges that could guide future operational improvements. 
